repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
        - id: trailing-whitespace
        - id: check-added-large-files
          args: [--maxkb=1000]
        - id: check-json
        - id: pretty-format-json
        - id: check-toml
        - id: check-yaml
        - id: end-of-file-fixer
        - id: no-commit-to-branch
          args: [--branch, master]
        - id: requirements-txt-fixer
        - id: trailing-whitespace
